CatchTheTornado/askql

- src/askscript/__tests__/06-comments/program16-comment.test.result.ts
- src/askscript/__tests__/90-misc/variable-shadowing-01.test.result.ts
- src/askvm/resources/core/return.ts
> fix(askvm): fix return

- .github/workflows/askql-ci.yaml
- .prettierignore
> feat(build): Run tests with GitHub actions

- .github/workflows/askql-ci.yaml
- .prettierignore
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- package.json
- prettier.config.js
- src/askvm/resources/core/delay.ts
- src/askvm/resources/math/index.ts
- src/cli.ts
> feat(CI): Prettier PR and push hooks

- jest.test.config.js
- package.json
- src/test.jest.testRunner.ts
- Should now run tests for `spec.ts` and `.tsx` files
- Now skips tests in the dist folder
> fix(tests): Fix running dist tests and tests not running

- tsconfig.json
> Exclude test files in tsconfig

- package-lock.json
- package.json
Used husky and lint-staged. It affects only files that were staged during the commit.
> feat(dev):Prettier pre-commit hook

- CONTRIBUTING.md
- README.md
> docs(CONTRIBUTING): closes #122

- src/askscript/__tests__/09-operators/operators-07-greater_than-oper.test.ts
- src/askscript/__tests__/09-operators/operators-07-greater_than-res.test.ts
- src/askscript/__tests__/09-operators/operators-07-greater_than.test.result.ts
- src/askvm/resources/math/greaterThan.ts
- src/askvm/resources/math/index.ts
I've just added greaterThan operator `>`.
Close #134
> feat(operator): greaterThan operator

- src/askExpressMiddleware/askExpressMiddleware.spec.ts
- src/askExpressMiddleware/askExpressMiddleware.ts
> feat: Add the express middleware

- .gitignore
- CONTRIBUTING.md
Expand Contributing guidelines by add Global .gitignore file configuration #120
> Docs: add information about global gitignore in guideline and change .gitignore (#120)

- .prettierignore
> fix(#118): fix Prettier fails when committing .askcode or .askjson files

- .prettierignore
> fix(#167): fix Prettier fails when committing .gitignore

- RELEASING.md
Let's write down some plan in terms of releasing AskQL
> docs: RELEASING.md

- src/__tests__/code2vm.ts
- src/askscript/__tests__/99-e2e-tests/_environment.ts
- src/askscript/__tests__/99-e2e-tests/e2e-13-philosophers.ask
- src/askscript/__tests__/99-e2e-tests/e2e-13-philosophers.askcode
- src/askscript/__tests__/99-e2e-tests/e2e-13-philosophers.askjson
- src/askscript/__tests__/99-e2e-tests/e2e-13-philosophers.test.result.ts
- src/askvm/lib/run.ts
- src/askvm/resources/list/__tests__/find.test.ts
- src/askvm/resources/list/find.ts
- src/utils/index.ts
> fix(call): add test case for philosophers

- src/askjsx/lib/While.tsx
- src/askscript/__tests__/04-control-flow/program11-while.ask
- src/askscript/__tests__/04-control-flow/program11-while.askcode
- src/askscript/__tests__/04-control-flow/program11-while.askjson
- src/askscript/__tests__/04-control-flow/program11-while.test.result.ts
- src/askscript/__tests__/12-newlines/newlines03-while.test.result.ts
- src/askvm/resources/core/fun.ts
- src/askvm/resources/core/while.ts
> fix(askvm): while

- .gitignore
- src/askExpressMiddleware/askExpressMiddleware.spec.ts
- src/askExpressMiddleware/askExpressMiddleware.ts
> Feat: Support both askcode and askscript in askExpressMiddleware

- package-lock.json
- package.json
- src/demoAskScriptServer.ts
Also remove try/catch from demoAskScriptServer
> refactor: lodash is now dev dep

- src/playground/public/assets/css/custom.css
- src/playground/public/assets/js/app.ts
- src/playground/public/assets/js/demos.ts
- src/playground/views/main.handlebars
Closes #173 
This version of Playground is available at: http://cli.askql.org:5000/
> fix(playground): update Run button and other small UI changes

- .env.example
- README.md
- src/playground/app.ts
- src/playground/views/main.handlebars
> feat(playground): add an optional support for Google Tag Manager

- .gitignore
- README.md
- netlify.toml
- package-lock.json
- package.json
- src/playground-backend/express/demoAskScriptServer.ts
- src/playground-backend/lambda/askscript.ts
- src/playground-backend/lambda/version.ts
- src/playground-backend/lib/resources.ts
- src/playground-backend/lib/utils.ts
- src/playground-backend/lib/values.ts
- src/playground/compile.ts
I submitted the backend part also as a separate PR: https://github.com/xFAANG/askql/pull/328
> feat(playground): implement frontend & backend for netlify, reorganize code

- src/askscript-vscode/.vscodeignore
- src/askscript-vscode/CHANGELOG.md
- src/askscript-vscode/README.md
- src/askscript-vscode/language-configuration.json
- src/askscript-vscode/package.json
- src/askscript-vscode/syntaxes/askscript.tmLanguage.json
- src/askscript-vscode/vsc-extension-quickstart.md
> feat(vscode): implement VSCode extension for .ask syntax highlighting

- src/playground/compile.ts
> fix(playground): add GA to the site for Netlify too

- README.md
Closes https://github.com/xFAANG/askql/issues/317
> fix(readme): update AskQL diagram

- src/askscript/__tests__/13-real-operators/real-operators-01e-exclamation.ask
- src/askscript/__tests__/13-real-operators/real-operators-01e-exclamation.ask.snapshot.tsx
- src/askscript/__tests__/13-real-operators/real-operators-01e-exclamation.askcode
- src/askscript/parser/askscript.grammar.pegjs
> feat(askscript): add exclamation mark (!) to operators (#295)

- src/askvm/resources/math/__tests__/min.test.ts
- src/askvm/resources/math/index.ts
- src/askvm/resources/math/min.ts
Passes all tests on running `npm test`. Couldn't figure the commented test case in the max.test.ts file which is marked as TODO. Hence, replicated the similar case in the min.test.ts as well and kept it commented and marked as TODO
> feat: min Closes #369

- src/askscript/__tests__/09-operators/operators-12-bitwiseOr-oper.test.ts
- src/askscript/__tests__/09-operators/operators-12-bitwiseOr-res.test.ts
- src/askvm/resources/math/__tests__/bitwiseOr.test.ts
- src/askvm/resources/math/bitwiseOr.ts
- src/askvm/resources/math/index.ts
added bitwiseOr resource (| binary operator) and respective tests.
> feat: add a 'bitwiseOr' resource (| binary operator)

- src/playground/public/assets/js/app.ts
> fix(playground): fix blink on Ctrl-S (issue #377)

- src/playground/views/main.handlebars
> fix(playground): fix links to resources and values (#398)

- package-lock.json
- package.json
- scripts/playgroundBuild.ts
> fix: create OS agnostic build command/s for rm and mkdir (#395)

- package-lock.json
- package.json
remove unset package
Issue: #435
> chore: remove npm-watch

- src/askscript/__tests__/07-arrays/program17h-array-filter.ask
- src/askscript/__tests__/07-arrays/program17h-array-filter.askcode
- src/askscript/__tests__/07-arrays/program17h-array-filter.ast.tsx
- src/askscript/__tests__/07-arrays/program17h-array-filter.test.result.ts
- src/askvm/resources/list/__tests__/filter.test.ts
- src/askvm/resources/list/filter.ts
- src/askvm/resources/list/index.ts
- src/utils/index.ts
> feat(array): add a filter method

- src/askvm/resources/list/__tests__/each.test.ts
- src/askvm/resources/list/__tests__/map.test.ts
Plus a small cleanup of `each`
> test: add immutability tests for map

- src/askvm/resources/core/__test__/let.test.ts
- src/askvm/resources/core/let.ts
Also added `let` and `assign` tests along with a const test
Closes #254 
Note to reviewer - #521 is a different PR. This PR is only here for #254 but while working on it I thought we should consider refactoring which I leave as an open question at the moment.
> fix(const): throw an error when assigning to const

- .github/workflows/build-on-windows.yml
- package.json
- scripts/playgroundPostBuild.ts
- scripts/postBuild.ts
> fix(build): fix playground build on windows

- src/askvm/resources/core/__test__/query.test.ts
note the TODO is a test we should decide if we want it or not (#312 )
> test(query): added query unit tests

- .github/ISSUE_TEMPLATE/feature_request.md
> feat(chore): feature request issue template

- .github/dependabot.yml
> chore: prevent Dependabot from creating PRs for patch updates
